name: eduregistryselab
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  cloud_firestore: ^5.6.1
=======
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  cloud_firestore: ^5.6.0
  intl: ^0.18.0 # Add the intl package for date formatting
  fl_chart: ^0.40.0 # Correct placement of the fl_chart dependency
  image_picker: ^0.8.6 # Added image_picker dependency for profile image feature
  shared_preferences: ^2.3.5
>>>>>>> parent of dc86632 (Latest Changes)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
